telepot.exception.TelegramError: ('Bad Request: message text is empty', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: message text is empty'})
Telegram update caused TelegramError when passing blank area to user from bot. It has been fixed.